- desafio-02/valdinei11/d02-primos.c
Solução do desafio 02 (números primos) adicionada - @valdinei11
> Solução do desafio 02 adicionada (valdinei11)

- desafio-06/lrlucena/desafio06.scala
A solução fica mais simples usando o método diff
> Simplificando a solução do Desafio 06

- desafio-02/anthonyfisicabsb/primos.py
Agora eu fiz do jeito certo, o pull request.
> desafio-02 python

- desafio-04/lrlucena/xadrez.scala
Solução do Desafio 04 na linguagem Scala
> Desafio 04 na linguagem Scala

- desafio-02/rafaeldss/listaprimos.py
> Desafio - 02

- desafio-02/choco02/Prime-numbers.py
> Desafio 02

- desafio-02/lucantas/primes.go
- desafio-02/lucantas/tooeasy.go
Solução utilizando função ProbablyPrime do pacote math/big da biblioteca padrão do Go
> Solução para desafio-02

- desafio-02/laurosn/primos.py
Proposta de solução para o desafio 2 - Participante Lauro Silveira Neto
> Solução desafio 2

- desafio-03/laurosn/palindromo.py
Solução do desafio 03 - Lauro Silveira Neto
> Solução do desafio 03

- desafio-05/laurosn/funcionarios.py
Proposta de solução para o desafio5
> Soluçao desafio 5 - Lauro Silveira Neto

- desafio-05/devmmaia/empresa.py
> Solução do desafio 5

- desafio-02/Note45/desafio_02.c
- desafio-03/Note45/desafio_03.c
Essas são minhas respostas para os desafios 2 e 3.
> Respostas dos desafios

- desafio-02/Matiusco/primos_python.py
Adicionando a resposta ao desafio 2: Language python.
> Resposta: Desafio 2 em python.

- .gitignore
- desafio-02/rodineicosta/numeros_primos.py
Solução para o Desafio #2 em Python.
> Solução Desafio #2

- desafio-07/anthonyfisicabsb/Desafio7.java
Fiz umas mudanças pequenas no código, mas a performance para o arquivo de 1 GB caiu em 1 minuto e alguns segundos.
> melhorando performance desafio 7

- desafio-02/JacksonOsvaldo/python/desafio02.py
- desafio-03/JacksonOsvaldo/python/desafio03.py
Inserindo Intervalo Numérico (1:10000).
> Inserindo Intervalo Numérico & Resposta do Desafio 03

- desafio-08/lrlucena/scala/desafio08.scala
Já validei a nova versão em https://osprogramadores.com/v/ .
> Simplificação da solução do desafio 08

- desafio-02/arlima/python/desafio2.py
Revisado. Agora somente um commit com o desafio 2.
> Adicionado desafio2 por arlima

- desafio-04/karinnecristina/python/xadrez.py
> Desafio-04 by karinnecristina

- desafio-10/lrlucena/scala/turing.scala
Simplificação da solução do desafio 10
> Refatorando a solução do desafio 10

- desafio-06/arlima/go/desafio6.go
Solução do desafio 6. Espero ter feito certo no git agora.
> Adicionando a solucao do desafio 6

- desafio-07/arlima/go/desafio7.go
MD5 para o arquivo de teste bate com 2b4fd25f11d75c285ec69ecac420bd07
> Adicionado e revisado o desafio 7

- desafio-05/arlima/go/desafio05.go
Resolvi refazer o desafio 5. Agora em go para aprender.
> Adicionada solução desafio 5 em go por arlima

- .travis.yml
- travis-ci/dircheck.sh
- travis-ci/gocheck.sh
- travis-ci/presubmit.sh
- travis-ci/pycheck.sh
- travis-ci/validator.sh
- Added go code checking.
- Re-factored the presubmits to allow selective testing.
- Travis configured to use matrices. All non-language tests for now
go in the python vm.
> Added go code checking, refactored presubmits.

- desafio-05/correaelias/pascal/desafio5.pas
Melhorias no parsing, principalmente de números de ponto flutuante.
> Melhorias no parsing, principalmente de números de ponto flutuante.

- desafio-05/leovano/rust/Cargo.toml
- desafio-05/leovano/rust/src/main.rs
Fix regression and reverse arguments order.
> Desafio 05 (leovano) - Workaround

- desafio-05/correaelias/pascal/desafio5.pas
int64 para salarios
uso de containers da biblioteca do compilador
> melhorias no parsing de strings(evito fazer copias)

- desafio-09/anthonyfisicabsb/java/Main.java
Fiz algumas melhorias no meu código com base nas propostas do Leovano.
> Melhorias na solucao do desafio 9

- desafio-05/gabrields/python/desafio5_parser.py
> Adicionar solucao python do desafio 5.

- desafio-05/correaelias/pascal/desafio5.pas
Segue a nova versão em pascal.
> reescrita do zero

- desafio-02/lisboalien/python/desafio02.py
Solução feita na linguagem python
> Inclusao da solucao do desafio-02 em python.

- desafio-03/lisboalien/python/desafio03.py
Inclusão da Solução do desafio-03 em python
> Solucao do desafio-03 em python @lisboalien

- desafio-02/caiomuniz/cpp/primos.cpp
- desafio-03/caiomuniz/cpp/palindromos.cpp
Desafios 02 e 03 realizados por @caiomuniz
Linguagem: C++
> Desafios por @caiomuniz: 02 e 03

- desafio-05/correaelias/pascal/desafio5.pas
-'GetString' (remoção da conversão implícita de C string para Pascal string)
-'GetNumber' (simplificação da função)
-Remoção do código de limpeza de memória alocada ao final do programa (deixo pro S.O.)
> Melhorias:

- desafio-02/gstfps/php/desafio2-primos.php
Minha solução para o desafio 02
> Solução do desafio 02 por @gstfps

- desafio-05/helioloureiro/go/company_reporter.go
> Desafio 5 em go.

- desafio-03/itsArthurAlves/c/desafio_03.c
> desafio03 Arthur Alves

- desafio-04/itsArthurAlves/cpp/desafio_04.cpp
Fiz alguns aditivos, como mostrar a coordenada e mapeamento de tabuleiro, obrigado.
> cpp desafio 4 - itsArthurAlves

- desafio-02/AnaPaulaMazi/javascript/#2Primos.js
Ola,
Segue o desafio-2 para verificação.
Desde já obrigada
> desafio-02 AnaPauladeMazi

- desafio-04/TeijiW/python/desafio04.py
Resolução do desafio 4 em python
> Resolução do desafio 4 em python

- desafio-02/TeijiW/go/main.go
> Resolução do desafio 2 em Go

- desafio-03/Mekylei-Belchior/python/desafio3.py
Submetendo solução em Python para o desafio 3.
> Solução em Python para o desafio 3

- desafio-06/potigol/potigol/README.md
- desafio-06/potigol/potigol/anagram.poti
O tempo de execução foi reduzido para menos de 60 segundos.
````terminal
$ time echo maryhadalittleox | potigol anagram.poti > maryhadalittleox.txt
real    0m48.343s
user    0m53.547s
sys     0m8.234s
````
> Melhorando o tempo de execução do desafio 06

- desafio-06/lrlucena/scala/README.md
- desafio-06/lrlucena/scala/desafio06.scala
```
time scala -save desafio06.scala maryhadalittleox > maryhadlittleox.txt
real    0m25.086s
user    0m25.797s
sys     0m3.188s
```
> Melhoria da solução do desafio 06 na linguagem Scala

- desafio-03/cbcalves/cpp/palindromos_numerico.cpp
- desafio-03/cbcalves/cpp/palindromos_string.cpp
02 soluções, uma com string, e outra invertendo o número por cálculos.
> Solução do desafio 03 em CPP.

- desafio-06/cbcalves/c/Makefile
- desafio-06/cbcalves/c/anagrama.c
Consegue solucionar em meio segundo (depende do processador, testei em um AMD Phenom 9650)
> Solução do desafio 06 em C

- desafio-02/MaurilhoB/javascript/#2Primos.js
> Solução Desafio 02

- desafio-02/redkaio/javascript/desafio_02_num_primo.js
- desafio-02/redkaio/javascript/readme.md
Linguagem utilizada: Javascript
> Inclusão da pasta do usuário @redkaio com a resolução do desafio 2

- desafio-02/TeijiW/java/desafio_2.java
> Solução do desafio 2 em Java

- desafio-03/TeijiW/java/desafio_3.java
> Solução do desafio 3 em Java

- desafio-07/cbcalves/cpp/tac.cpp
A primeira versão alocava e liberava a memória várias vezes.
Agora ele aloca a memória apenas uma vez.
> Melhor eficiência no uso da memória

- desafio-08/cbcalves/cpp/fracoes.cpp
- Foi removida a string de entrada, não trabalhando mais
com transformações de texto.
- Redução do número de condicionais.
- Usando agora uma fórmula de MDC.
> Aumento de eficiencia

- desafio-11/cbcalves/c/primospi.c
- Melhora no algoritmo utlizando sort e limitando a procura na array.
- Aumentando a velocidade, a criação de threads ficou "cara" não sendo
mais recomendada.
> Maior eficiencia com ganho de velocidade

- desafio-11/cbcalves/cpp/primospi.cpp
- Mudança de estratégia para solucionar o problema.
- Sem necessidade de utilizar threads devido ao ganho de velocidade com a
nova estratégia.
> Mudança no algoritmo

- desafio-05/cbcalves/c/v3/d5_v3.c
- desafio-05/cbcalves/c/v3/uthash_mod.h
Melhoramentos da v3 após analises de performance, substituindo funções
> Desafio 05

- desafio-14/cbcalves/cpp/expressoes.cpp
A primeira versão da solução é difícil de entender,
esta é mais elegante, e de melhor leitura.
> Desafio 14

- desafio-02/bernardocamps/swift/primos.swift
Proposta de resolução do Desafio 02 em Swift.
> Desafio 02 em Swift - bernardocamps

- .gitignore
- desafio-03/bernardocamps/swift/palindromos.swift
Proposta de resolução do Desafio 03 em Swift.
> Desafio 03 em Swift - bernardocamps

- desafio-03/TeijiW/elixir/palindromes/.gitignore
- desafio-03/TeijiW/elixir/palindromes/README.md
- desafio-03/TeijiW/elixir/palindromes/lib/palindromes.ex
- desafio-03/TeijiW/elixir/palindromes/mix.exs
- desafio-03/TeijiW/elixir/palindromes/test/palindromes_test.exs
- desafio-03/TeijiW/elixir/palindromes/test/test_helper.exs
Leia o README.md para instruções de como rodar o código.
> Desafio 03 em Elixir

- desafio-02/ThiagoCostaBarbosa/javascript/desafio02.js
Resolução do Desafio 02 em Javascript do site: https://osprogramadores.com/desafios/d02/
> Add Desafio02

- desafio-04/ThiagoCostaBarbosa/javascript/desafio04.js
Resolução do Desafio 04 em Javascript do site: https://osprogramadores.com/desafios/d04/
> Add Desafio04

- desafio-03/ThiagoCostaBarbosa/javascript/desafio03.js
Resolução do Desafio 03 em Javascript do site: https://osprogramadores.com/desafios/d03/
> Add Desafio03

- desafio-02/guiribeirodev/javascript/desafio-02.js
> Realização do exercício 02 - Números primos.

- desafio-02/alleSilva/elixir/README.md
- desafio-02/alleSilva/elixir/list_primes.exs
Programa em elixir usando recursao, para listar os primos entre 1 e 10000.
> programa lista primos

- desafio-03/guiribeirodev/javascript/index.js
> Solução Exercício 03 - Palíndromos.

- desafio-04/guiribeirodev/javascript/index.js
> Resolução exercício 04 - Xadrez.

- desafio-03/ThiagoCostaBarbosa/javascript/desafio03.js
> Code Refactored: Desafio 3

- desafio-07/alexandrempierre/python/main.py
- desafio-07/alexandrempierre/python/reverseread.py
UNIX tac resolvido em Python usando generators.
> Desafio 07 resolvido

- desafio-04/alexandrempierre/python/main.py
Coloquei mais um commit para remover o teste do nome de módulo.
> Desafio 04 resolvido em Python

- desafio-03/alexsandro-matias/python/desafio_03.py
Consertando a árvore de diretórios novamente com mais um novo branch
> consertando os erros da árvore de diretório

- desafio-03/luizfelmach/python/desafio3.py
To run this code:
`python desafio3.py
`
Then, give data entry.
For example:
```
>>> python desafio3.py
>>> 1 20
>>> [1, 2, 3, 4, 5, 6, 7, 8, 9, 11]
```
> Desafio 3 em python - @luizfelmach

- desafio-12/luizfelmach/python/desafio12.py
Atualização da saída do desafio 12 para uma melhor visualização.
Antes:
`16 true 4
`
Depois:
```
Number: 16
Is power of 2: true
Exponent: 4
```
> Atualiza desafio 12 em Python - @luizfelmach

- desafio-07/luizfelmach/cpp/desafio7.cpp
- desafio-07/luizfelmach/cpp/makefile
Para rodar o código:
```properties
make build
make run
```
> Desafio 7 em C++ - @luizfelmach

- desafio-02/DanielRosa74/java/PrimeNumbers.java
Solution to the second challenge in Java
> Added solution to desafio-02

- desafio-03/caviuna/python/palindromicos.py
- desafio-03/caviuna/python/readme.md
Desafio 03 Palíndromos em python3.
> desafio 03 -python- By @Caviuna

- desafio-02/OtnielSSilva/c/main.c
Desafio 02 concluído em c.
Postei o código no replit para facilitar a visualização: https://replit.com/@OtnielSSilva/Algoritmos-com-C#main.c
> Desafio 02 em c

- README.md
- Melhorias no texto da documentação, explicando problemas mais comuns.
- Introduz a idéia de linguagens aceitas (testes de presubmit serão
modificados a seguir para enforçar o padrão).
> Melhorias na documentação do op-desafios.

- ci/dircheck.sh
- Melhorias na documentação do op-desafios.
- Adiciona suporte a linguagens/desafios obsoletos.
> Adiciona suporte a linguagens/desafios obsoletos.

- desafio-06/guiribeirodev/javascript/README.md
- desafio-06/guiribeirodev/javascript/index.js
> Resolução desafio 06 - Anagramas.

- desafio-02/aCube1/c/Makefile
- desafio-02/aCube1/c/primes.c
Use o Makefile para compilar.
Somente testando com Clang.
> Conclusão do desafio 02.

- desafio-03/aCube1/c/Makefile
- desafio-03/aCube1/c/palindromes.c
Use o Makefile para compilar.
Somente testando com Clang.
Verifica palíndromos de 1 a 10.000.
> Conclusão do desafio 03.

- desafio-03/AlexandreOliver/csharp/Program.cs
- desafio-03/AlexandreOliver/csharp/csharp.csproj
Editei a pasta .gitignore adicionando as pastas obj/ e bin/, sao pastas de configuração do Dotnet.
> Resolução do Desafio 03

- desafio-02/hoklifter/python/primos.py
Corrigido o diretório duplicado.
> Desafio 2.

- desafio-02/hydraxler/python/primos.py
Resetei meu repositório local, estou reenviando o pull request de forma mais organizada agora, com apenas 1 commit.
> Resolução do desafio 2.

- desafio-02/jorge-tarin/javascript/desafio.js
@mpinheir, para que não ocorra validações em excesso implementei a divisão apenas até a raiz quadrada de X.
> Desafio 02 em JS

- desafio-03/jorge-tarin/javascript/desafio.js
- desafio-03/jorge-tarin/javascript/readme.md
@mpinheir , implementei uma melhoria para que o usuário passe os números como parâmetro ao rodar o arquivo, assim como uma validação se de fato foram enviados números ou um texto qualquer.
> Desafio 03 em JS

- desafio-07/guiribeirodev/python/README.md
- desafio-07/guiribeirodev/python/main.py
> Complete exercise 07

- desafio-07/valdineijunior/javascript/unixTac.js
Para rodar o programa utilize "node unixTac.js arquivo.txt"
Para rodar limitando a memória utilizada para 512M utilize "node --max-old-space-size=512 unixTac.js arquivo.txt"
Onde arquivo.txt pode ser substituido pelo arquivo que deseja ler.
versão do node utilizada v18.16.0.
> Resolução desafio 07 Valdinei Junior

- desafio-14/lucasfturos/csharp/.gitignore
- desafio-14/lucasfturos/csharp/.valid
- desafio-14/lucasfturos/csharp/Program.cs
- desafio-14/lucasfturos/csharp/build.sh
- desafio-14/lucasfturos/csharp/expressao.csproj
Para usar só executar o arquivo bash build.sh, se precisar, use o chmod +x build.sh para tornar ele executável.
```
./build.sh
```
> Desafio 14 em C#

- desafio-02/wasluissp/cpp/primo.cpp
Changes to be committed:
new file:   desafio-02/wasluissp/cpp/primo.cpp
>  Solução Desafio 02

- .gitignore
- README.md
Nesse PR foram propostas duas sugestões de melhorias: 
1. **d3804c5** Adicionadas pastas dos binários (bin e obj) de .NET ao git ignore global do repo
1. **a07efba** Correção de alguns typos no README principal
> Duas sugestões de melhorias

- desafio-02/disouzam/python/.gitignore
- desafio-02/disouzam/python/README.md
- desafio-02/disouzam/python/numeros_primos.py
Esse PR contém a solução do desafio 02, em Python, que consiste em imprimir os números primos entre 1 e 10000, inclusive.
1. **e1fea6f** Solução para o desafio 2 - Imprimir números primos entre 1 e 10000, inclusive.
- .gitignore adicionado para não comitar acidentalmente arquivos de configuração do ambiente Python
Arquivos adicionados:
- desafio-02/disouzam/python/.gitignore
- desafio-02/disouzam/python/README.md
- desafio-02/disouzam/python/numeros_primos.py
> Desafio 02 - Números primos (Python)

- desafio-02/shamanime/go/README.md
- desafio-02/shamanime/go/desafio02.go
- desafio-02/shamanime/go/desafio02_test.go
- desafio-02/shamanime/go/go.mod
Solução do desafio 02 usando Go.
> Desafio 02 - shamanime/go

- desafio-03/shamanime/go/README.md
- desafio-03/shamanime/go/desafio03.go
- desafio-03/shamanime/go/desafio03_test.go
- desafio-03/shamanime/go/go.mod
Solução do desafio 03 usando Go.
> Desafio 03 - shamanime/go

- desafio-03/disouzam/python/.gitignore
- desafio-03/disouzam/python/README.md
- desafio-03/disouzam/python/palindromos.py
Um único script foi criado para processar dois números fornecidos e retornar uma lista separada por vírgulas, como sugerido no enunciado do desafio # 03 (https://osprogramadores.com/desafios/d03/). A determinação se um número é ou não palíndromo foi feita através da conversão do número em uma string e posterior reversão da string usando recursos nativos da linguagem Python. Se a string original e a versão revertida forem iguais, determina-se que o número é palíndromo. 
Nenhum esforço foi feito para tratar cenários onde zeros à esquerda são passados como argumento. 
Para testar a execução do script basta executar os comandos abaixo, a partir da raiz do repositório:
```shell
cd desafio-03/disouzam/python
python -m palindromos limite_inferior limite_superior
```
onde limite_inferior e …
> Desafio 03 -Palíndromos (Python)

- desafio-02/victorvssouza/javascript/README.md
- desafio-02/victorvssouza/javascript/main.js
Script em JavaScript para verificar e listar os números primos de 1 até 1000. 
Testado e corrigido de acordo com o padrão do Online linter (op-desafios).
> Desafio 2: Script em JS para listar números primos de 1 a 1000

- desafio-02/LeonardRuhmann/javascript/primos.js
Este pull request introduz um conjunto de algoritmos em JavaScript para identificar números primos e não primos em arrays.
> desafio-02

- desafio-03/victorvssouza/javascript/main.js
Código em JS para encontrar os números palíndromos entre um intervalo determinado pelo usuário.
> Desafio 03 - Codigo em JS para encontrar os números palindromos 

- desafio-03/leandro208/cpp/README.md
- desafio-03/leandro208/cpp/palindromo.cpp
Resolvendo o desafio 03 para verificar os palíndromos entre o intervalo digitado.
> feat: resolvendo o desafio 03

- desafio-02/eduardoconde-bit/php/README.md
- desafio-02/eduardoconde-bit/php/index.php
consistindo na exibição de todos os números primos até um intervalo definido (10000), utilizando-se  do crivo de Erastótenes para filtrar os primos presentes no intervalo e subsequentemente fazer a exibição dos valores.
> Desafio 02 - @eduardoconde-bit

- desafio-03/eduardoconde-bit/python/README.md
- desafio-03/eduardoconde-bit/python/palindrome.py
Resolução do desafio 03 sobre números palíndromos em Python!
> Desafio 03 - @eduardoconde-bit

- desafio-02/Donicad/python/README.md
- desafio-02/Donicad/python/n_primos.py
Solução para o desafio 02 ajustada, adicionei um arquivo README.md como foi solicitado explicando sobre o código.
> Desafio 02 por @Donicad

- desafio-07/rocketguedes/python/README.md
- desafio-07/rocketguedes/python/tac.py
> #7 Challenge - Solution

- desafio-03/RaudineiMauricio/python/README.md
- desafio-03/RaudineiMauricio/python/numeros_palindromos.py
Criei uma nova branch e enviei.
> Desafio 03 Feito por @RaudineiMauricio

- desafio-03/AlexPHorta/python/README.md
- desafio-03/AlexPHorta/python/desafio03.py
Olá, segue minha resposta para o desafio 3.
> Minha tentativa de resposta ao desafio 3.

- desafio-03/miguelvitta/c/Makefile
- desafio-03/miguelvitta/c/README.md
- desafio-03/miguelvitta/c/desafio-03.c
O linter reclama do uso do scanf. Eu ainda não sei usar outro meio, e caso seja necessário, aprenderei. Mas como perguntei no grupo e não obtive resposta, decidi upar o desafio aqui onde terei resposta com certeza.
> Adds the solution to the desafio-03, palindromomos, problem
